name: solid_software_test
description: "A Solid Software Test Task Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  bloc: ^8.1.4
  dartz: ^0.10.1
  easy_localization: ^3.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  injectable: ^2.4.1
  logger: ^2.2.0


dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.1
  injectable_generator: ^2.6.1
  mockito: ^5.4.4
  solid_lints: ^0.1.5


flutter:
  uses-material-design: true
  assets:
    - assets/localization/

